### ISSUE TITLE
启动bbr失败

### ISSUE THREAD

**Issue by hiperioncn** [Sherlockwoo/shadowsocksR_1nstall#1]
[信息] 检测内核最新版本中...
[信息] 当前内核最新版本为 : 4.10.12
[信息] 检测到 内核版本 已满足要求，继续...
[信息] 检测到 BBR 已开启 !
[错误] 检测到 BBR 已开启但未正常启动，请检查 !

**Comment by ghost** [comment]
推荐使用Debian 7 x64系统
